name: "Update DockerHub Info"
on:
  push:
    branches:
      - master
    paths:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  diagnostics:
    name: Log Workflow Information
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Git Revision"
        run: echo "${GITHUB_REF}"
      - name: "Github Event"
        run: echo -e '${{ toJSON(github.event) }}'

  update-info:
    name: Update Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Push Info to Repos"
        env:
          DOCKERHUB_USER_NAME: "reitzig"
          DOCKERHUB_ACCESS_TOKEN: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
        run: |
          for p in profiles/*; do
            p=$(basename ${p})
            .github/scripts/update-dockerhub-info.sh ${p%.profile}
          done

  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
